name: Run Unit Tests
on: [push, pull_request]
jobs:
  run-CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.6, 3.7, 3.8, 3.9]
        exclude:
          - os: macos-latest
            python: 3.6
          - os: macos-latest
            python: 3.7
          - os: macos-latest
            python: 3.8
          - os: windows-latest
            python: 3.6
          - os: windows-latest
            python: 3.7
          - os: windows-latest
            python: 3.8
    steps:
      - uses: actions/checkout@v2

      - name: Python Version ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools tox tox-gh-actions

      - name: Test with tox
        run: tox
        env:
          TOX_SKIP_ENV: coverage,GHA-coverage

      - name: Lint
        if: ${{ matrix.python == '3.9' && runner.os == 'Linux'}}
        run: tox -e lint

      - name: isort
        if: ${{ matrix.python == '3.9' && runner.os == 'Linux'}}
        run: tox -e isort-check


      - name: Build Coverage
        if: ${{ matrix.python == '3.9' && runner.os == 'Linux'}}
        run: tox -e GHA-coverage

      - name: Upload Coveralls
        if: ${{ matrix.python == '3.9' && runner.os == 'Linux'}}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.xml
